### ISSUE TITLE
timeline_simile.phtml

### ISSUE THREAD

**Issue by gjerdery** [Daniel-KM/Omeka-S-module-Timeline#10]
In a fresh install of the master branch, I've been receiving a Zend error saying that "common/block-layout/timeline_simile" was unable to be found when I tried to view a timeline placed on a page.

The commit from April 7, 2019, renamed the path for timeline_simile.phtml from "common/block-layout/timeline_simile.phtml" to "asset/vendor/simile/timeline_simile.phtml." By copying this file over into the expected directory, I'm able to view the timeline, since this is the path set in line 129 of src/Site/BlockLayout/Timeline.php.

**Comment by Becklighter** [comment]
I encountered the exact same issue.

**Comment by Daniel-KM** [comment]
Yes, it's a missing template. I updated it for Omeka 2 too.
