### ISSUE TITLE
Incompatibility with Omeka S v. 2+?

### ISSUE THREAD

**Issue by joebauer** [Daniel-KM/Omeka-S-module-Timeline#11]
Uploaded the plugin to an Omeka S version 2.0.2 environment, but then got the following error. I assume this means the Module isn't compatible with version 2? 

![image](https://user-images.githubusercontent.com/6989685/66568615-d1607900-eb37-11e9-8d77-2577e66c3fc6.png)

**Comment by Daniel-KM** [comment]
Ye, it''s probably not working yet. I'm currently checking all my modules. To test, just change the version in config/module.ini.

**Comment by Daniel-KM** [comment]
It's upgraded (3.4.9).
