### ISSUE TITLE
Trailing quote and semicolon in Knightlab script

### ISSUE THREAD

**Issue by ManOnDaMoon** [Daniel-KM/Omeka-S-module-Timeline#13]
On line 21, a trailing quote and semicolon prevent the script execution.

https://github.com/Daniel-KM/Omeka-S-module-Timeline/blob/3dbdc4f3cc72e0cddff79759446ee9a89a893f83/view/common/block-layout/timeline_knightlab.phtml#L21

**Comment by Daniel-KM** [comment]
Thanks, it's fixed.
