### ISSUE TITLE
Incompatability with Omeka-S

### ISSUE THREAD

**Issue by zkapfumvuti** [Daniel-KM/Omeka-S-module-Timeline#17]
Hi Daniel,

May you kindly assist with configuring the correct version in order for this module to work.

I am on an Ubuntu 18.04 LTS server running Omeka-S.

![omeka version](https://user-images.githubusercontent.com/60696384/73843201-d8b63b80-4826-11ea-9919-5e16c6590dc2.png)
![module version](https://user-images.githubusercontent.com/60696384/73843206-da7fff00-4826-11ea-8899-ef5ad8f0f399.png)

**Comment by Daniel-KM** [comment]
Can you give me the logs of Omeka or your server?

**Comment by zkapfumvuti** [comment]
[new_error.log](https://github.com/Daniel-KM/Omeka-S-module-Timeline/files/4184865/new_error.log)
[access.log](https://github.com/Daniel-KM/Omeka-S-module-Timeline/files/4184866/access.log)
[error.log](https://github.com/Daniel-KM/Omeka-S-module-Timeline/files/4184868/error.log)
[application.log](https://github.com/Daniel-KM/Omeka-S-module-Timeline/files/4184869/application.log)
[new_access.log](https://github.com/Daniel-KM/Omeka-S-module-Timeline/files/4184870/new_access.log)

**Comment by zkapfumvuti** [comment]
All resolved by downgrading my version of PHP to version 7.2 from version 7.4 I also had to assign root under privileges to my MySQL database user.

**Comment by daniel-gitter** [comment]
Ok, so there were two errors, incompatibility with 7.4 and issue with mysql (module log has issue too).

**Comment by Daniel-KM** [comment]
Probably fixed in last version.
