### ISSUE TITLE
Knightlab producing Zend error

### ISSUE THREAD

**Issue by sbucdh** [Daniel-KM/Omeka-S-module-Timeline#20]
We're getting a Zend error when using Timeline 3.4.12 with the Knightlab library on an Omeka S 2.1 test site with the last few releases of Timeline module. Was hoping newest release would fix it but I guess the problem is on our end. It works perfectly on our production site which is still running S 1.4 with Timeline 3.4.5  It works fine with the Simile library on 2.1 but when switched to Knightlab this is the result:

`Zend\Router\Exception\InvalidArgumentException
Missing parameter "block-id"

Details:

Zend\Router\Exception\InvalidArgumentException: Missing parameter "block-id" in /space/omekaS_2.1/vendor/zendframework/zend-router/src/Http/Segment.php:309
Stack trace:
#0 /space/omekaS_2.1/vendor/zendframework/zend-router/src/Http/Segment.php(423): Zend\Router\Http\Segment->buildPath(Array, Array, false, false, Array)
#1 /space/omekaS_2.1/vendor/zendframework/zend-router/src/Http/TreeRouteStack.php(391): Zend\Router\Http\Segment->assemble(Array, Array)
#2 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Helper/Url.php(106): Zend\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 [internal function]: Zend\View\Helper\Url->__invoke('timeline-block', Array)
#4 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Zend\View\Helper\Url), Array)
#5 /space/omekaS_2.1/themes/jjavits/view/common/block-layout/timeline_knightlab.phtml(11): Zend\View\Renderer\PhpRenderer->__call('url', Array)
#6 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/space/omekaS_2...')
#7 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Helper/Partial.php(62): Zend\View\Renderer\PhpRenderer->render(NULL, NULL)
#8 [internal function]: Zend\View\Helper\Partial->__invoke('common/block-la...', Array)
#9 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Zend\View\Helper\Partial), Array)
#10 /space/omekaS_2.1/modules/Timeline/src/Site/BlockLayout/Timeline.php(152): Zend\View\Renderer\PhpRenderer->__call('partial', Array)
#11 /space/omekaS_2.1/application/src/View/Helper/BlockLayout.php(124): Timeline\Site\BlockLayout\Timeline->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#12 /space/omekaS_2.1/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#13 /space/omekaS_2.1/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/space/omekaS_2...')
#14 /space/omekaS_2.1/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#15 /space/omekaS_2.1/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#16 /space/omekaS_2.1/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#17 /space/omekaS_2.1/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#18 /space/omekaS_2.1/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#19 /space/omekaS_2.1/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#20 /space/omekaS_2.1/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#21 /space/omekaS_2.1/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#22 /space/omekaS_2.1/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#23 /space/omekaS_2.1/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#24 /space/omekaS_2.1/index.php(21): Zend\Mvc\Application->run()
#25 {main}`

We are currently running PHP 7.2.34 with Zend engine 3.2.0 and MariaDB 10.1.47

**Comment by Daniel-KM** [comment]
This is probably related to your theme (see # 5): the code in the default view is 
`var jsonTimelineUri = <?= json_encode($this->url('timeline-block', ['block-id' => $block->id()]), 320) ?>;`
So check if the block-id is set.

**Comment by sbucdh** [comment]
Thank you for quick reply! - this fixed the issue.
