### ISSUE TITLE
Color coding tags on Timeline

### ISSUE THREAD

**Issue by NehaBasera** [Daniel-KM/Omeka-S-module-Timeline#24]
Hello,

Is there any possible way to color code the tags on timeline based on certain fields like Title, Author or Description.
I am trying to assign different colors to tags(highlighted in attached image) appearing on timeline based on a field. However, I couldn't find any solution to do it directly or by changing the javascript code.

![timeline_highlighted](https://user-images.githubusercontent.com/47417870/181425975-53c28b91-1604-4ee3-9093-d9deb38e42ec.JPG)

If possible, Could you please suggest any solution or methods to change the code to implement color coding?

Thank you for your attention.

**Comment by ParthLPatel** [comment]
Hello Contributors,

Is there any specific way around grouping the content (individual itemset) on the timeline and perform the color coding for the categories of the content (individual itemset) on the timeline.


Thanks!!

**Comment by Daniel-KM** [comment]
These points requires developments to add the data in the json.
