### ISSUE TITLE
194 error

### ISSUE THREAD

**Issue by morarchives** [Daniel-KM/Omeka-S-module-Timeline#25]
Hello,
I have installed Timeline version 3.4.16.3 on Omeka S Version 3.2.0 it threw an error on the first run. I have tried narrowing the amount of items to less than twenty and no change.

The date centering is also not working, it stay focus on todays date.

Thanks for your help.

Here is the Application Log data:
2022-10-18T21:30:08+00:00 ERR (3): Doctrine\ORM\EntityNotFoundException: Entity of type 'Omeka\Entity\SitePage' for IDs id(30) was not found in /home/****/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:46
Stack trace:
#0 /home/****/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(156): Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier('Omeka\\Entity\\Si...', Array)
#1 /home/****/public_html/application/data/doctrine-proxies/__CG__OmekaEntitySitePage.php(277): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineProxies\__CG__\Omeka\Entity\SitePage), 'getSite', Array)
#2 /home/****/public_html/application/data/doctrine-proxies/__CG__OmekaEntitySitePage.php(277): Closure->__invoke(Object(DoctrineProxies\__CG__\Omeka\Entity\SitePage), 'getSite', Array)
#3 /home/****/public_html/modules/Timeline/src/Controller/ApiController.php(80): DoctrineProxies\__CG__\Omeka\Entity\SitePage->getSite()
#4 /home/****/public_html/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(382): Timeline\Controller\ApiController->getList()
#5 /home/****/public_html/application/src/Controller/ApiController.php(168): Laminas\Mvc\Controller\AbstractRestfulController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#6 /home/****/public_html/modules/Timeline/src/Controller/ApiController.php(186): Omeka\Controller\ApiController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /home/****/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Timeline\Controller\ApiController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /home/****/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /home/****/public_html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /home/****/public_html/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(312): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /home/****/public_html/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractRestfulController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#12 /home/****/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#13 /home/****/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#14 /home/****/public_html/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#15 /home/****/public_html/index.php(21): Laminas\Mvc\Application->run()
#16 {main}

And here are some screenshots:
![image](https://user-images.githubusercontent.com/114703264/196987263-791e6bce-4665-4320-8ddd-d229b4b62ed6.png)
![image](https://user-images.githubusercontent.com/114703264/196987651-6ed9e2fb-7d26-457f-9805-89ec847870a7.png)

**Comment by flamsens** [comment]
I can confirm this problem (Omeka-S 3.2.3). Timeline version 3.4.12.3.3 works, versions 3.4.13.3 and above all have this issue.

**Comment by Daniel-KM** [comment]
There is a fix in version 3.4.17, but this issue is strange : there is a block, but no page for it.

**Comment by Daniel-KM** [comment]
Is the page private?
