### ISSUE TITLE
Negative date range

### ISSUE THREAD

**Issue by Frederic-P** [Daniel-KM/Omeka-S-module-Timeline#3]
Hello,

I have an issue with the Omeka-S Timeline Module when using negative dateranges on an item.

The daterange I need is `-2700/-2601` (positive dateranges work without an issue using this format)

I can use the negative date value in the Timeline Module configuration when setting //page> Timeline > Options > Center date to -YYYY. 

I am still using the default viewer information, css etc... so nothing has changed codewise to the Module.

The errormessage is visible on the page where an item is included that has a negative daterange. The error message is: "Failed to load json data from /omeka/timeline/3/events.json Internal Server Error" in an alert box. On the background the spinner is loading until I dismiss the alert box.

I get no additional information regarding this error in the console. I have also installed the log modules for Omeka S, yet nothing shows up in that section. 

**Technical information**
- OS: Ubuntu 16.04 LTS (running in VM) 64 bit
- Browser: Firefox 59.0.2 (64bit)
- Timeline version: 3.4.4.
- Omeka S Version V1.1.1. (fresh install)
- Timeline library: Simile (not using the Internal library)

**Comment by Daniel-KM** [comment]
Thanks for your detailled issue! I just fixed it in the last commit.
